AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Auth:
        DefaultAuthorizer: SessionAuthorizer
        Authorizers:
          SessionAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !Sub ${SessionAuthFunction.Arn}
            Identity:
              ReauthorizeEvery: 0
              Headers:
                - Authorization

  SessionAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      CodeUri: src/authorizer/session_auth_function
      Handler: lambda_handler.lambda_handler

  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      CodeUri: src/apis/app_function
      Handler: lambda_handler.lambda_handler
      Events:
        ApiGatewayIntegration:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: get
